# ============================================================================
# FILE: sasclouds/constants.py – Satellite groups, config paths, logging setup
# ============================================================================
"""
Constants and configuration for the SASClouds API integration.

Extracted from the monolithic sasclouds_api_scraper.py (1438 lines).
"""

import logging
from pathlib import Path

# ── Application directories ──────────────────────────────────────────────────
_APP_DIR = Path(__file__).resolve().parent
LOG_DIR = _APP_DIR.parent / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

_CONFIG_PATH = _APP_DIR.parent / "config.json"

# ── Logging setup ────────────────────────────────────────────────────────────
_logger = logging.getLogger(__name__)
_logger.setLevel(logging.DEBUG)

_api_log_path = LOG_DIR / "api_interactions.jsonl"
_api_log_path.parent.mkdir(parents=True, exist_ok=True)

# ── Satellite and sensor definitions ──────────────────────────────────────────
# satelliteId  = value sent in the API payload (confirmed from HAR 2026-05-06
#                where noted; best-guess otherwise).
# displayName  = label shown in the website UI (used in the sidebar).
# sensorIds    = sensor/mode codes as used on the website.
SATELLITE_GROUPS = {
    "Optical": {
        "2-meter": [
            {"satelliteId": "ZY3-1",   "displayName": "ZY3-01",   "sensorIds": ["MUX", "NAD", "DLC"]},
            {"satelliteId": "ZY3-2",   "displayName": "ZY3-02",   "sensorIds": ["MUX", "NAD", "DLC"]},
            {"satelliteId": "ZY3-3",   "displayName": "ZY3-03",   "sensorIds": ["MUX", "NAD", "DLC"]},
            {"satelliteId": "ZY02C",   "displayName": "ZY1-02C",  "sensorIds": ["HRC", "PMS"]},
            {"satelliteId": "ZY1-02D", "displayName": "ZY1-02D",  "sensorIds": ["VNIC"]},
            {"satelliteId": "ZY1-02E", "displayName": "ZY1-02E",  "sensorIds": ["VNIC"]},
            {"satelliteId": "2m8m",    "displayName": "2m/8m",    "sensorIds": ["PMS"]},
            {"satelliteId": "GF1",     "displayName": "GF-1",     "sensorIds": ["PMS"]},
            {"satelliteId": "GF6",     "displayName": "GF-6",     "sensorIds": ["PMS"]},
            {"satelliteId": "CB04A",   "displayName": "CBERS-04A","sensorIds": ["WPM"]},
            {"satelliteId": "CM1",     "displayName": "CM1",      "sensorIds": ["DMC"]},
            {"satelliteId": "TH01",    "displayName": "TH01",     "sensorIds": ["GFB", "DGP"]},
            {"satelliteId": "SPOT6/7", "displayName": "SPOT-6/7", "sensorIds": ["PMS"]},
        ],
        "Sub-meter": [
            {"satelliteId": "GF2",    "displayName": "GF-2",   "sensorIds": ["PMS"]},
            {"satelliteId": "GF7",    "displayName": "GF-7",   "sensorIds": ["MUX", "BWD", "FWD"]},
            {"satelliteId": "GFDM01", "displayName": "GFDM01", "sensorIds": ["PMS"]},
        ],
        "Other": [
            {"satelliteId": "JL1KF01B",  "displayName": "JL-1(1m)",   "sensorIds": []},
            {"satelliteId": "JL1KF01C",  "displayName": "JL-1(0.5m)", "sensorIds": []},
            {"satelliteId": "BJ2",       "displayName": "BJ-2",       "sensorIds": []},
            {"satelliteId": "BJ3",       "displayName": "BJ-3",       "sensorIds": []},
            {"satelliteId": "SV1",       "displayName": "SV-1",       "sensorIds": []},
            {"satelliteId": "SV2",       "displayName": "SV-2",       "sensorIds": []},
            {"satelliteId": "LJ3-2",     "displayName": "LJ3-2",      "sensorIds": []},
            {"satelliteId": "GeoEye-1",  "displayName": "GeoEye-1",   "sensorIds": []},
            {"satelliteId": "WorldView-2","displayName": "WorldView-2","sensorIds": []},
            {"satelliteId": "WorldView-3","displayName": "WorldView-3","sensorIds": []},
            {"satelliteId": "WorldView-4","displayName": "WorldView-4","sensorIds": []},
            {"satelliteId": "Pleiades",  "displayName": "Pleiades",   "sensorIds": []},
            {"satelliteId": "DEIMOS",    "displayName": "DEIMOS",     "sensorIds": []},
            {"satelliteId": "KOMPSAT-2", "displayName": "KOMPSAT-2",  "sensorIds": []},
            {"satelliteId": "KOMPSAT-3", "displayName": "KOMPSAT-3",  "sensorIds": []},
            {"satelliteId": "KOMPSAT-3A","displayName": "KOMPSAT-3A", "sensorIds": []},
            {"satelliteId": "GF1",  "displayName": "GF-1",  "sensorIds": ["WFV"]},
        ],
    },
    "SAR": [
        {"satelliteId": "GF3",     "displayName": "GF-3",     "sensorIds": []},
        {"satelliteId": "GF3B",    "displayName": "GF-3B",    "sensorIds": []},
        {"satelliteId": "GF3C",    "displayName": "GF-3C",    "sensorIds": []},
        {"satelliteId": "GF3D",    "displayName": "GF-3D",    "sensorIds": []},
        {"satelliteId": "GF3E",    "displayName": "GF-3E",    "sensorIds": []},
        {"satelliteId": "GF3F",    "displayName": "GF-3F",    "sensorIds": []},
        {"satelliteId": "GF3G",    "displayName": "GF-3G",    "sensorIds": []},
        {"satelliteId": "LT1",     "displayName": "LT-1",     "sensorIds": []},
        {"satelliteId": "LT2",     "displayName": "LT-2",     "sensorIds": []},
        {"satelliteId": "HJ1C",    "displayName": "HJ-1C",    "sensorIds": []},
        {"satelliteId": "RS1",     "displayName": "RS-1",     "sensorIds": []},
        {"satelliteId": "RS2",     "displayName": "RS-2",     "sensorIds": []},
        {"satelliteId": "RS3",     "displayName": "RS-3",     "sensorIds": []},
        {"satelliteId": "PIESAT1", "displayName": "PIESAT-1", "sensorIds": []},
        {"satelliteId": "PIESAT2", "displayName": "PIESAT-2", "sensorIds": []},
        {"satelliteId": "SJ1",     "displayName": "SJ-1",     "sensorIds": []},
        {"satelliteId": "SJ2",     "displayName": "SJ-2",     "sensorIds": []},
        {"satelliteId": "SJ3",     "displayName": "SJ-3",     "sensorIds": []},
        {"satelliteId": "SJ4",     "displayName": "SJ-4",     "sensorIds": []},
        {"satelliteId": "SJ5",     "displayName": "SJ-5",     "sensorIds": []},
        {"satelliteId": "SJ6",     "displayName": "SJ-6",     "sensorIds": []},
        {"satelliteId": "SJ7",     "displayName": "SJ-7",     "sensorIds": []},
        {"satelliteId": "SJ8",     "displayName": "SJ-8",     "sensorIds": []},
        {"satelliteId": "SJ9",     "displayName": "SJ-9",     "sensorIds": []},
        {"satelliteId": "SJ10",    "displayName": "SJ-10",    "sensorIds": []},
        {"satelliteId": "SJ11",    "displayName": "SJ-11",    "sensorIds": []},
        {"satelliteId": "SJ12",    "displayName": "SJ-12",    "sensorIds": []},
        {"satelliteId": "SJ13",    "displayName": "SJ-13",    "sensorIds": []},
        {"satelliteId": "SJ14",    "displayName": "SJ-14",    "sensorIds": []},
        {"satelliteId": "SJ15",    "displayName": "SJ-15",    "sensorIds": []},
        {"satelliteId": "SJ16",    "displayName": "SJ-16",    "sensorIds": []},
        {"satelliteId": "SJ17",    "displayName": "SJ-17",    "sensorIds": []},
        {"satelliteId": "SJ18",    "displayName": "SJ-18",    "sensorIds": []},
        {"satelliteId": "SJ19",    "displayName": "SJ-19",    "sensorIds": []},
        {"satelliteId": "SJ20",    "displayName": "SJ-20",    "sensorIds": []},
        {"satelliteId": "SJ21",    "displayName": "SJ-21",    "sensorIds": []},
        {"satelliteId": "SJ22",    "displayName": "SJ-22",    "sensorIds": []},
        {"satelliteId": "SJ23",    "displayName": "SJ-23",    "sensorIds": []},
        {"satelliteId": "SJ24",    "displayName": "SJ-24",    "sensorIds": []},
        {"satelliteId": "SJ25",    "displayName": "SJ-25",    "sensorIds": []},
        {"satelliteId": "SJ26",    "displayName": "SJ-26",    "sensorIds": []},
        {"satelliteId": "SJ27",    "displayName": "SJ-27",    "sensorIds": []},
        {"satelliteId": "SJ28",    "displayName": "SJ-28",    "sensorIds": []},
        {"satelliteId": "SJ29",    "displayName": "SJ-29",    "sensorIds": []},
        {"satelliteId": "SJ30",    "displayName": "SJ-30",    "sensorIds": []},
        {"satelliteId": "SJ31",    "displayName": "SJ-31",    "sensorIds": []},
        {"satelliteId": "SJ32",    "displayName": "SJ-32",    "sensorIds": []},
        {"satelliteId": "SJ33",    "displayName": "SJ-33",    "sensorIds": []},
        {"satelliteId": "SJ34",    "displayName": "SJ-34",    "sensorIds": []},
        {"satelliteId": "SJ35",    "displayName": "SJ-35",    "sensorIds": []},
        {"satelliteId": "SJ36",    "displayName": "SJ-36",    "sensorIds": []},
        {"satelliteId": "SJ37",    "displayName": "SJ-37",    "sensorIds": []},
        {"satelliteId": "SJ38",    "displayName": "SJ-38",    "sensorIds": []},
        {"satelliteId": "SJ39",    "displayName": "SJ-39",    "sensorIds": []},
        {"satelliteId": "SJ40",    "displayName": "SJ-40",    "sensorIds": []},
        {"satelliteId": "SJ41",    "displayName": "SJ-41",    "sensorIds": []},
        {"satelliteId": "SJ42",    "displayName": "SJ-42",    "sensorIds": []},
        {"satelliteId": "SJ43",    "displayName": "SJ-43",    "sensorIds": []},
        {"satelliteId": "SJ44",    "displayName": "SJ-44",    "sensorIds": []},
        {"satelliteId": "SJ45",    "displayName": "SJ-45",    "sensorIds": []},
        {"satelliteId": "SJ46",    "displayName": "SJ-46",    "sensorIds": []},
        {"satelliteId": "SJ47",    "displayName": "SJ-47",    "sensorIds": []},
        {"satelliteId": "SJ48",    "displayName": "SJ-48",    "sensorIds": []},
        {"satelliteId": "SJ49",    "displayName": "SJ-49",    "sensorIds": []},
        {"satelliteId": "SJ50",    "displayName": "SJ-50",    "sensorIds": []},
        {"satelliteId": "SJ51",    "displayName": "SJ-51",    "sensorIds": []},
        {"satelliteId": "SJ52",    "displayName": "SJ-52",    "sensorIds": []},
        {"satelliteId": "SJ53",    "displayName": "SJ-53",    "sensorIds": []},
        {"satelliteId": "SJ54",    "displayName": "SJ-54",    "sensorIds": []},
        {"satelliteId": "SJ55",    "displayName": "SJ-55",    "sensorIds": []},
        {"satelliteId": "SJ56",    "displayName": "SJ-56",    "sensorIds": []},
        {"satelliteId": "SJ57",    "displayName": "SJ-57",    "sensorIds": []},
        {"satelliteId": "SJ58",    "displayName": "SJ-58",    "sensorIds": []},
        {"satelliteId": "SJ59",    "displayName": "SJ-59",    "sensorIds": []},
        {"satelliteId": "SJ60",    "displayName": "SJ-60",    "sensorIds": []},
        {"satelliteId": "SJ61",    "displayName": "SJ-61",    "sensorIds": []},
        {"satelliteId": "SJ62",    "displayName": "SJ-62",    "sensorIds": []},
        {"satelliteId": "SJ63",    "displayName": "SJ-63",    "sensorIds": []},
        {"satelliteId": "SJ64",    "displayName": "SJ-64",    "sensorIds": []},
        {"satelliteId": "SJ65",    "displayName": "SJ-65",    "sensorIds": []},
        {"satelliteId": "SJ66",    "displayName": "SJ-66",    "sensorIds": []},
        {"satelliteId": "SJ67",    "displayName": "SJ-67",    "sensorIds": []},
        {"satelliteId": "SJ68",    "displayName": "SJ-68",    "sensorIds": []},
        {"satelliteId": "SJ69",    "displayName": "SJ-69",    "sensorIds": []},
        {"satelliteId": "SJ70",    "displayName": "SJ-70",    "sensorIds": []},
        {"satelliteId": "SJ71",    "displayName": "SJ-71",    "sensorIds": []},
        {"satelliteId": "SJ72",    "displayName": "SJ-72",    "sensorIds": []},
        {"satelliteId": "SJ73",    "displayName": "SJ-73",    "sensorIds": []},
        {"satelliteId": "SJ74",    "displayName": "SJ-74",    "sensorIds": []},
        {"satelliteId": "SJ75",    "displayName": "SJ-75",    "sensorIds": []},
        {"satelliteId": "SJ76",    "displayName": "SJ-76",    "sensorIds": []},
        {"satelliteId": "SJ77",    "displayName": "SJ-77",    "sensorIds": []},
        {"satelliteId": "SJ78",    "displayName": "SJ-78",    "sensorIds": []},
        {"satelliteId": "SJ79",    "displayName": "SJ-79",    "sensorIds": []},
        {"satelliteId": "SJ80",    "displayName": "SJ-80",    "sensorIds": []},
        {"satelliteId": "SJ81",    "displayName": "SJ-81",    "sensorIds": []},
        {"satelliteId": "SJ82",    "displayName": "SJ-82",    "sensorIds": []},
        {"satelliteId": "SJ83",    "displayName": "SJ-83",    "sensorIds": []},
        {"satelliteId": "SJ84",    "displayName": "SJ-84",    "sensorIds": []},
        {"satelliteId": "SJ85",    "displayName": "SJ-85",    "sensorIds": []},
        {"satelliteId": "SJ86",    "displayName": "SJ-86",    "sensorIds": []},
        {"satelliteId": "SJ87",    "displayName": "SJ-87",    "sensorIds": []},
        {"satelliteId": "SJ88",    "displayName": "SJ-88",    "sensorIds": []},
        {"satelliteId": "SJ89",    "displayName": "SJ-89",    "sensorIds": []},
        {"satelliteId": "SJ90",    "displayName": "SJ-90",    "sensorIds": []},
        {"satelliteId": "SJ91",    "displayName": "SJ-91",    "sensorIds": []},
        {"satelliteId": "SJ92",    "displayName": "SJ-92",    "sensorIds": []},
        {"satelliteId": "SJ93",    "displayName": "SJ-93",    "sensorIds": []},
        {"satelliteId": "SJ94",    "displayName": "SJ-94",    "sensorIds": []},
        {"satelliteId": "SJ95",    "displayName": "SJ-95",    "sensorIds": []},
        {"satelliteId": "SJ96",    "displayName": "SJ-96",    "sensorIds": []},
        {"satelliteId": "SJ97",    "displayName": "SJ-97",    "sensorIds": []},
        {"satelliteId": "SJ98",    "displayName": "SJ-98",    "sensorIds": []},
        {"satelliteId": "SJ99",    "displayName": "SJ-99",    "sensorIds": []},
        {"satelliteId": "SJ100",   "displayName": "SJ-100",   "sensorIds": []},
        {"satelliteId": "SJ101",   "displayName": "SJ-101",   "sensorIds": []},
        {"satelliteId": "SJ102",   "displayName": "SJ-102",   "sensorIds": []},
        {"satelliteId": "SJ103",   "displayName": "SJ-103",   "sensorIds": []},
        {"satelliteId": "SJ104",   "displayName": "SJ-104",   "sensorIds": []},
        {"satelliteId": "SJ105",   "displayName": "SJ-105",   "sensorIds": []},
        {"satelliteId": "SJ106",   "displayName": "SJ-106",   "sensorIds": []},
        {"satelliteId": "SJ107",   "displayName": "SJ-107",   "sensorIds": []},
        {"satelliteId": "SJ108",   "displayName": "SJ-108",   "sensorIds": []},
        {"satelliteId": "SJ109",   "displayName": "SJ-109",   "sensorIds": []},
        {"satelliteId": "SJ110",   "displayName": "SJ-110",   "sensorIds": []},
        {"satelliteId": "SJ111",   "displayName": "SJ-111",   "sensorIds": []},
        {"satelliteId": "SJ112",   "displayName": "SJ-112",   "sensorIds": []},
        {"satelliteId": "SJ113",   "displayName": "SJ-113",   "sensorIds": []},
        {"satelliteId": "SJ114",   "displayName": "SJ-114",   "sensorIds": []},
        {"satelliteId": "SJ115",   "displayName": "SJ-115",   "sensorIds": []},
        {"satelliteId": "SJ116",   "displayName": "SJ-116",   "sensorIds": []},
        {"satelliteId": "SJ117",   "displayName": "SJ-117",   "sensorIds": []},
        {"satelliteId": "SJ118",   "displayName": "SJ-118",   "sensorIds": []},
        {"satelliteId": "SJ119",   "displayName": "SJ-119",   "sensorIds": []},
        {"satelliteId": "SJ120",   "displayName": "SJ-120",   "sensorIds": []},
        {"satelliteId": "SJ121",   "displayName": "SJ-121",   "sensorIds": []},
        {"satelliteId": "SJ122",   "displayName": "SJ-122",   "sensorIds": []},
        {"satelliteId": "SJ123",   "displayName": "SJ-123",   "sensorIds": []},
        {"satelliteId": "SJ124",   "displayName": "SJ-124",   "sensorIds": []},
        {"satelliteId": "SJ125",   "displayName": "SJ-125",   "sensorIds": []},
        {"satelliteId": "SJ126",   "displayName": "SJ-126",   "sensorIds": []},
        {"satelliteId": "SJ127",   "displayName": "SJ-127",   "sensorIds": []},
        {"satelliteId": "SJ128",   "displayName": "SJ-128",   "sensorIds": []},
        {"satelliteId": "SJ129",   "displayName": "SJ-129",   "sensorIds": []},
        {"satelliteId": "SJ130",   "displayName": "SJ-130",   "sensorIds": []},
        {"satelliteId": "SJ131",   "displayName": "SJ-131",   "sensorIds": []},
        {"satelliteId": "SJ132",   "displayName": "SJ-132",   "sensorIds": []},
        {"satelliteId": "SJ133",   "displayName": "SJ-133",   "sensorIds": []},
        {"satelliteId": "SJ134",   "displayName": "SJ-134",   "sensorIds": []},
        {"satelliteId": "SJ135",   "displayName": "SJ-135",   "sensorIds": []},
        {"satelliteId": "SJ136",   "displayName": "SJ-136",   "sensorIds": []},
        {"satelliteId": "SJ137",   "displayName": "SJ-137",   "sensorIds": []},
        {"satelliteId": "SJ138",   "displayName": "SJ-138",   "sensorIds": []},
        {"satelliteId": "SJ139",   "displayName": "SJ-139",   "sensorIds": []},
        {"satelliteId": "SJ140",   "displayName": "SJ-140",   "sensorIds": []},
        {"satelliteId": "SJ141",   "displayName": "SJ-141",   "sensorIds": []},
        {"satelliteId": "SJ142",   "displayName": "SJ-142",   "sensorIds": []},
        {"satelliteId": "SJ143",   "displayName": "SJ-143",   "sensorIds": []},
        {"satelliteId": "SJ144",   "displayName": "SJ-144",   "sensorIds": []},
        {"satelliteId": "SJ145",   "displayName": "SJ-145",   "sensorIds": []},
        {"satelliteId": "SJ146",   "displayName": "SJ-146",   "sensorIds": []},
        {"satelliteId": "SJ147",   "displayName": "SJ-147",   "sensorIds": []},
        {"satelliteId": "SJ148",   "displayName": "SJ-148",   "sensorIds": []},
        {"satelliteId": "SJ149",   "displayName": "SJ-149",   "sensorIds": []},
        {"satelliteId": "SJ150",   "displayName": "SJ-150",   "sensorIds": []},
        {"satelliteId": "SJ151",   "displayName": "SJ-151",   "sensorIds": []},
        {"satelliteId": "SJ152",   "displayName": "SJ-152",   "sensorIds": []},
        {"satelliteId": "SJ153",   "displayName": "SJ-153",   "sensorIds": []},
        {"satelliteId": "SJ154",   "displayName": "SJ-154",   "sensorIds": []},
        {"satelliteId": "SJ155",   "displayName": "SJ-155",   "sensorIds": []},
        {"satelliteId": "SJ156",   "displayName": "SJ-156",   "sensorIds": []},
        {"satelliteId": "SJ157",   "displayName": "SJ-157",   "sensorIds": []},
        {"satelliteId": "SJ158",   "displayName": "SJ-158",   "sensorIds": []},
        {"satelliteId": "SJ159",   "displayName": "SJ-159",   "sensorIds": []},
        {"satelliteId": "SJ160",   "displayName": "SJ-160",   "sensorIds": []},
        {"satelliteId": "SJ161",   "displayName": "SJ-161",   "sensorIds": []},
        {"satelliteId": "SJ162",   "displayName": "SJ-162",   "sensorIds": []},
        {"satelliteId": "SJ163",   "displayName": "SJ-163",   "sensorIds": []},
        {"satelliteId": "SJ164",   "displayName": "SJ-164",   "sensorIds": []},
        {"satelliteId": "SJ165",   "displayName": "SJ-165",   "sensorIds": []},
        {"satelliteId": "SJ166",   "displayName": "SJ-166",   "sensorIds": []},
        {"satelliteId": "SJ167",   "displayName": "SJ-167",   "sensorIds": []},
        {"satelliteId": "SJ168",   "displayName": "SJ-168",   "sensorIds": []},
        {"satelliteId": "SJ169",   "displayName": "SJ-169",   "sensorIds": []},
        {"satelliteId": "SJ170",   "displayName": "SJ-170",   "sensorIds": []},
        {"satelliteId": "SJ171",   "displayName": "SJ-171",   "sensorIds": []},
        {"satelliteId": "SJ172",   "displayName": "SJ-172",   "sensorIds": []},
        {"satelliteId": "SJ173",   "displayName": "SJ-173",   "sensorIds": []},
        {"satelliteId": "SJ174",   "displayName": "SJ-174",   "sensorIds": []},
        {"satelliteId": "SJ175",   "displayName": "SJ-175",   "sensorIds": []},
        {"satelliteId": "SJ176",   "displayName": "SJ-176",   "sensorIds": []},
        {"satelliteId": "SJ177",   "displayName": "SJ-177",   "sensorIds": []},
        {"satelliteId": "SJ178",   "displayName": "SJ-178",   "sensorIds": []},
        {"satelliteId": "SJ179",   "displayName": "SJ-179",   "sensorIds": []},
        {"satelliteId": "SJ180",   "displayName": "SJ-180",   "sensorIds": []},
        {"satelliteId": "SJ181",   "displayName": "SJ-181",   "sensorIds": []},
        {"satelliteId": "SJ182",   "displayName": "SJ-182",   "sensorIds": []},
        {"satelliteId": "SJ183",   "displayName": "SJ-183",   "sensorIds": []},
        {"satelliteId": "SJ184",   "displayName": "SJ-184",   "sensorIds": []},
        {"satelliteId": "SJ185",   "displayName": "SJ-185",   "sensorIds": []},
        {"satelliteId": "SJ186",   "displayName": "SJ-186",   "sensorIds": []},
        {"satelliteId": "SJ187",   "displayName": "SJ-187",   "sensorIds": []},
        {"satelliteId": "SJ188",   "displayName": "SJ-188",   "sensorIds": []},
        {"satelliteId": "SJ189",   "displayName": "SJ-189",   "sensorIds": []},
        {"satelliteId": "SJ190",   "displayName": "SJ-190",   "sensorIds": []},
        {"satelliteId": "SJ191",   "displayName": "SJ-191",   "sensorIds": []},
        {"satelliteId": "SJ192",   "displayName": "SJ-192",   "sensorIds": []},
        {"satelliteId": "SJ193",   "displayName": "SJ-193",   "sensorIds": []},
        {"satelliteId": "SJ194",   "displayName": "SJ-194",   "sensorIds": []},
        {"satelliteId": "SJ195",   "displayName": "SJ-195",   "sensorIds": []},
        {"satelliteId": "SJ196",   "displayName": "SJ-196",   "sensorIds": []},
        {"satelliteId": "SJ197",   "displayName": "SJ-197",   "sensorIds": []},
        {"satelliteId": "SJ198",   "displayName": "SJ-198",   "sensorIds": []},
        {"satelliteId": "SJ199",   "displayName": "SJ-199",   "sensorIds": []},
        {"satelliteId": "SJ200",   "displayName": "SJ-200",   "sensorIds": []},
    ],
}
