# config package — Application configuration
from config.constants import (
    EARTH_RADIUS_KM,
    EARTH_EQUATORIAL_RADIUS_KM,
    EARTH_POLAR_RADIUS_KM,
    CET,
    MAP_TILES,
    DEFAULT_CENTER,
    DEFAULT_ZOOM,
    AOI_ZOOM,
    SENSOR_COLORS,
)
from config.satellites import (
    SATELLITES,
    get_satellite_by_norad,
    get_satellites_by_provider,
    get_satellites_by_type,
    get_all_sar_satellites,
    get_all_optical_satellites,
    get_all_cameras,
    get_satellite_count,
    export_to_json,
    add_custom_satellite,
)

__all__ = [
    "EARTH_RADIUS_KM",
    "EARTH_EQUATORIAL_RADIUS_KM",
    "EARTH_POLAR_RADIUS_KM",
    "CET",
    "MAP_TILES",
    "DEFAULT_CENTER",
    "DEFAULT_ZOOM",
    "AOI_ZOOM",
    "SENSOR_COLORS",
    "SATELLITES",
    "get_satellite_by_norad",
    "get_satellites_by_provider",
    "get_satellites_by_type",
    "get_all_sar_satellites",
    "get_all_optical_satellites",
    "get_all_cameras",
    "get_satellite_count",
    "export_to_json",
    "add_custom_satellite",
]
